### ISSUE TITLE
job pagination

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/chokhmah#8]
Pagination should be available for job queries.

Consider how endpoints like github work: https://developer.github.com/v3/guides/traversing-with-pagination/

* provide next + last link

given a jobs endpoint, to use pagination the response would include two elements:
* additionalJobs=TRUE/FALSE
* nextJobID = next job in the pagination list
* per_page = default 100, max=20000 maybe (lets calculate the size of json, how many jobs for say up to 5 MB of json - roughly 5-7 MB for 20k jobs seems to be it)

## considerations

* jobs may be adjusted between queries, so we should be very careful around overfetching/underfetching or if in general the stats change between queries.

* error codes?:
  * no jobs available
  * overfetched (index not found)

@Blackglade can you find out what github does in these types of scenarios (eg what happens if you query for more issues past pagination limit, or query a repo for issues that has no issues, or query open issues when it has issues, but no open issues

## potential api

`jobs?startJobID=<id>&quan

**Comment by Blackglade** [comment]
It's similar to the v4 GraphQL API response in that it returns an empty array instead of an array of issue objects for a repo that has no issues/no open issues. As far as pagination goes, there will be no url link that is returned.

**Comment by shairozan** [comment]
Got this in #9

**Comment by shairozan** [comment]
@dpastoor After the pull for pagination do we want to call this closed? I think there was still some debate on the response structure.
